### ISSUE TITLE
Date entry for new project on Dev throws an error

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/hca-ebi-dev-team#342] opened 2020-10-07 09:51 UTC
https://dev.contribute.data.humancellatlas.org/projects/register

I entered a date in 2021, but it throws an error, wouldn't let me register the project. 
Also - the user flow here is that if there's something wrong with the date, the error should be shown within this page, not when you try to submit in that big red box.

gabs

**Comment by clairerye** [comment] 2020-10-07 09:59
It works on staging so is this due to one of the new changes @MightyAx ?

**Comment by MightyAx** [comment] 2020-10-07 12:55
I investigated this with gabs and the cause was actually not having provided a response for one of the required fields (Institution on contact)

The registration form validation hasn't changed it doesn't identify problems in real time, and the message of missing fields doesn't identify what the problem are.

**Comment by clairerye** [comment] 2020-10-12 10:15
Closing this as its not a bug as suggested in the title but the fact that we don't have live validation. This is a feature we definitely need but we aren't doing this work right now.

**Closed by clairerye** 2020-10-12 10:15 UTC
