### ISSUE TITLE
[Exporter] Submission Flow States (Phase 1)

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-dev-team#156] opened 2020-06-08 10:17 UTC
As a contributor I want to know where my dataset is in the overall flow of archiving and exporting to DCP2.
[Design Document](https://docs.google.com/document/d/11NAxNDQ5m-32aEgDkvkwYPWd4pjexspbbncDtpdpjk4/edit#)

1. Use the submission states from the flow below

[![](https://mermaid.ink/img/eyJjb2RlIjoic3RhdGVEaWFncmFtXG5bKl0gLS0-IFBlbmRpbmdcblBlbmRpbmcgLS0-IERyYWZ0XG5EcmFmdCAtLT4gVmFsaWRhdGluZ1xuVmFsaWRhdGluZyAtLT4gVmFsaWRcblZhbGlkIC0tPiBEcmFmdFxuVmFsaWRhdGluZyAtLT4gSW52YWxpZFxuSW52YWxpZCAtLT4gRHJhZnRcblZhbGlkIC0tPiBTdWJtaXR0ZWQgOiBzdWJtaXQgdG8gaGNhP1xuVmFsaWQgLS0-IFN1Ym1pdHRlZCA6IHN1Ym1pdCB0byBhcmNoaXZlcyBhbmQgZ2V0IGFjY2Vzc2lvbnM_XG5TdWJtaXR0ZWQgLS0-IFByb2Nlc3NpbmdcblN1Ym1pdHRlZCAtLT4gRXhwb3J0aW5nXG5Qcm9jZXNzaW5nIC0tPiBBcmNoaXZpbmdcbkFyY2hpdmluZyAtLT4gQXJjaGl2ZWRcbkFyY2hpdmVkIC0tPiBFeHBvcnRpbmcgOiBzdWJtaXQgdG8gaGNhP1xuRXhwb3J0aW5nIC0tPiBFeHBvcnRlZFxuRXhwb3J0ZWQgLS0-IENsZWFudXAgOiBkZWxldGUgZGF0YSBmaWxlcz9cbkNsZWFudXAgLS0-IENvbXBsZXRlZFxuQ29tcGxldGVkIC0tPiBbKl1cbiBcbm5vdGUgcmlnaHQgb2YgUHJvY2Vzc2luZ1xuICAgIEdlbmVyYXRpbmcgbWFuaWZlc3RzXG4gICAgV2lsbCB0cnkgdG8gcmVtb3ZlIHRoaXMgaW4gdGhlIG5lYXIgZnV0dXJlXG5lbmQgbm90ZVxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic3RhdGVEaWFncmFtXG5bKl0gLS0-IFBlbmRpbmdcblBlbmRpbmcgLS0-IERyYWZ0XG5EcmFmdCAtLT4gVmFsaWRhdGluZ1xuVmFsaWRhdGluZyAtLT4gVmFsaWRcblZhbGlkIC0tPiBEcmFmdFxuVmFsaWRhdGluZyAtLT4gSW52YWxpZFxuSW52YWxpZCAtLT4gRHJhZnRcblZhbGlkIC0tPiBTdWJtaXR0ZWQgOiBzdWJtaXQgdG8gaGNhP1xuVmFsaWQgLS0-IFN1Ym1pdHRlZCA6IHN1Ym1pdCB0byBhcmNoaXZlcyBhbmQgZ2V0IGFjY2Vzc2lvbnM_XG5TdWJtaXR0ZWQgLS0-IFByb2Nlc3NpbmdcblN1Ym1pdHRlZCAtLT4gRXhwb3J0aW5nXG5Qcm9jZXNzaW5nIC0tPiBBcmNoaXZpbmdcbkFyY2hpdmluZyAtLT4gQXJjaGl2ZWRcbkFyY2hpdmVkIC0tPiBFeHBvcnRpbmcgOiBzdWJtaXQgdG8gaGNhP1xuRXhwb3J0aW5nIC0tPiBFeHBvcnRlZFxuRXhwb3J0ZWQgLS0-IENsZWFudXAgOiBkZWxldGUgZGF0YSBmaWxlcz9cbkNsZWFudXAgLS0-IENvbXBsZXRlZFxuQ29tcGxldGVkIC0tPiBbKl1cbiBcbm5vdGUgcmlnaHQgb2YgUHJvY2Vzc2luZ1xuICAgIEdlbmVyYXRpbmcgbWFuaWZlc3RzXG4gICAgV2lsbCB0cnkgdG8gcmVtb3ZlIHRoaXMgaW4gdGhlIG5lYXIgZnV0dXJlXG5lbmQgbm90ZVxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)

**Comment by aaclan-ebi** [comment] 2020-06-09 17:57
I think this is a duplicate of #154. Changes needed for the TerraData Repo exporter should already be tracked there.

**Comment by aaclan-ebi** [comment] 2020-06-29 08:45
Released in prod last 25th June.
Changelog: https://github.com/ebi-ait/ingest-kube-deployment/blob/master/production/changelog.md#25-june-2020

**Closed** 2020-07-08 15:27 UTC
