### ISSUE TITLE
HCA Ontology release 1.0.23

### ISSUE THREAD

**Issue by zoependlington** [ebi-ait/hca-ebi-dev-team#409] opened 2021-04-19 14:27 UTC
The [HCA Ontology release 1.0.22](https://github.com/ebi-ait/ontology/releases/tag/1.0.22) is out and and needs to be picked up. Tag should also be available automatically on Quay.io.

Could the OLS instance/EBI environment be reloaded and the validator cache cleared please?

Thank you!

Tagging @pnejad to keep her in the loop :)

**Comment by MightyAx** [comment] 2021-04-20 08:49
Can this be covered by our manual GtLab pipeline @jacobwindsor?
If so can you show me how?

**Comment by MightyAx** [comment] 2021-04-20 10:00
Otherwise: manual SOP: https://ebi-ait.github.io/hca-ebi-dev-team/operations_tasks/HCAO-release.html

**Comment by pnejad** [comment] 2021-04-20 14:43
@MightyAx  Do you have an estimate of when the release will be complete? We have a few datasets that are blocked from submission by this.

**Comment by MightyAx** [comment] 2021-04-20 15:24
Should be in the next 30 minutes

**Comment by MightyAx** [comment] 2021-04-20 15:36
Actually, please disregard my above comment, [the Quay.io build is failing](https://quay.io/repository/ebi-ait/ontology/build/7142056c-ce7b-434c-8415-1ea424dc0d4b) due to an issue pulling from docker hub, we will need to change the hosting of the docker builds to our own service to fix this issue.

Hopefully we will be able to update you regarding this tomorrow.

**Comment by MightyAx** [comment] 2021-04-20 16:12
The ontology service cannot be built on quay.io because of docker rate limiting the pull of image `simonjupp/ebi-ols:3.1.1` so we have hosted the base image on [quay.io](https://quay.io/repository/ebi-ait/ingest-base-images?tab=tags) `quay.io/ebi-ait/ingest-base-images:ebi-ols_3.1.1 `

This change of hosting requires the ontology dockerfile to change which I have started by creating [ebi-ait/ontology#2](https://github.com/ebi-ait/ontology/pull/2)

Once this PR is merged the quay.io build will trigger and build the ontology service without hitting the docker rate limits and we can then deploy the ontology service to our environments using the [standard process](https://ebi-ait.github.io/hca-ebi-dev-team/operations_tasks/HCAO-release.html).

When deploying please include @jacobwindsor who wants to make sure the manual process of deployments runs smoothly in light of the recent gitlab developments.

Also one unknown that should be updated into the above guide is: Do ontology releases progress through the usual ingest deployment chain from dev to staging to production?

**Comment by aaclan-ebi** [comment] 2021-04-21 15:05
@zoependlington I think we need a new tag because of the docker file update. Is it okay if I increment the version to be 1.0.23 ? Will this cause any issues on your end?

**Comment by aaclan-ebi** [comment] 2021-04-21 15:06
By increment, i meant tagging a new version 1.0.23.

**Comment by zoependlington** [comment] 2021-04-21 15:24
Hi @aaclan-ebi, that would cause a lot of issues with next month's release, unfortunately, as the release pipeline automatically tags the ontology incrementally i.e. next release would be 1.0.23. Would it be possible to maintain 1.0.22 in the tag name and perhaps add something else distinctive e.g. 1.0.22a?

**Comment by aaclan-ebi** [comment] 2021-04-21 16:02
I see. Yes, that should work, thanks! I tagged the latest image built as 1.0.22a. Will deploy this in dev now and run our tests. There's a problem in our dev and staging env at the moment so it might be promoted to prod a bit later, hopefully by tomorrow.

**Comment by zoependlington** [comment] 2021-04-21 16:02
Thanks @aaclan-ebi! If there's anything else I can do to help, please let me know :)

**Comment by pnejad** [comment] 2021-04-21 16:18
@aaclan-ebi Could you ping Rachel and me when it is complete? Here or on slack :)

**Comment by aaclan-ebi** [comment] 2021-04-22 08:07
Promoted to prod. Tests are passing. 

Sure @pnejad!

**Comment by aaclan-ebi** [comment] 2021-04-22 10:36
Hi @zoependlington , @rays22 raised an issue to us on slack about the ontology updates. Do you have any thoughts? 


> Today I encountered a validation issue with one of the ontology terms that passed Ingest validation yesterday.
> The term [full length single cell RNA sequencing](http://www.ebi.ac.uk/efo/EFO_0008441) is a child of [assay](http://purl.obolibrary.org/obo/OBI_0000070) in the latest EFO,
> yet I am getting this validation error in Ingest:
>    "errorType" : "METADATA_ERROR",
>     "message" : "Provided term is not child of [http://purl.obolibrary.org/obo/OBI_0000070]",
>     "userFriendlyMessage" : "Provided term is not child of [http://purl.obolibrary.org/obo/OBI_0000070] at .method.ontology",
>     "absoluteDataPath" : ".method.ontology"
> 
> The very same term passed validation yesterday.
> When I check the term on the HCA custom OLS (Updated 21 Apr 2021 14:42), there the term full length single cell RNA sequencing is only in the transcription profiling branch and not under assay:
> <https://ontology.archive.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0008441>
> I am wondering if the problem is on our side or with the upstream ontology subset which was imported/updated yesterday?

**Comment by zoependlington** [comment] 2021-04-22 10:40
@aaclan-ebi I believe this is related to the issue which caused us to need a patch release on EFO earlier this week. If this is a seriously breaking issue, I can run a new release of HCAO with the updated EFO slim?

**Comment by rays22** [comment] 2021-04-22 10:46
I am afraid it is a blocker. The validation issue prevents us from exporting new datasets for the HCA DCP.

**Comment by zoependlington** [comment] 2021-04-22 10:47
@rays22 I will try and get a new release out this afternoon, apologies!

@aaclan-ebi Should I comment on this ticket when the new release is out or open a new one?

**Comment by aaclan-ebi** [comment] 2021-04-22 10:55
@zoependlington Please just add the new version in this ticket. Thanks a lot for fixing it!

**Comment by zoependlington** [comment] 2021-04-22 11:45
@aaclan-ebi The new release (1.0.23) is now out and available here: https://github.com/ebi-ait/ontology/releases/tag/1.0.23

Please let me know if there are any issues!

**Comment by aaclan-ebi** [comment] 2021-04-22 12:42
@zoependlington @rays22 the new version has been released.

**Comment by zoependlington** [comment] 2021-04-22 12:44
Thank you, @aaclan-ebi!

CCing @paolaroncaglia @pnejad

**Comment by rays22** [comment] 2021-04-22 12:58
I can confirm that the issue has been solved by the new release.
Thank you both @zoependlington and @aaclan-ebi for fixing it so quickly! :1st_place_medal:

**Comment by pnejad** [comment] 2021-04-22 16:14
Thank you all for resolving this issue so quickly!!

**Comment by rachadele** [comment] 2021-04-22 16:31
![Screen Shot 2021-04-22 at 9 30 55 AM](https://user-images.githubusercontent.com/51383714/115750941-8a1e8f80-a34d-11eb-82a0-7098628ab0ee.png)

Still seeing this after the ontology release

**Comment by paolaroncaglia** [comment] 2021-04-23 15:42
@rachadele 
@pnejad 
Please let us know if the validation report is still failing, and if so, how can we help. @zoependlington looked into this too but we don't have enough info to assist further. We'll pick up any comments or messages on Monday morning.
Thanks, and have a nice weekend,
Paola and Zoe

**Comment by paolaroncaglia** [comment] 2021-04-27 14:56
Hi @pnejad and @rachadele,
Following a brief conversation with Rachel on Slack, and a longer discussion with @zoependlington , here is our suggestion to address the validation report error above:

- [ ] I will modify EFO:0010892 'hydrolisis collection protocol' so that it's not a protocol term anymore, but rather a child of EFO:0011026 'enzyme-free chemical dissociation'. That will place it in the 'experimental process' branch. We assume that that's what the error message is referring to, but please confirm as we weren't able to locate .method.ontology among the metadata schema files. In fact, making sure we understand what that validation report is looking for would decrease chances of future issues. So that when an HCA wrangler asks for a new EFO term, however that term may be phrased in the paper/dataset you're looking at, we can ensure we add it in the appropriate branch in the ontology, i.e. within the appropriate HCA metadata context. Also, please let us know if you anticipate ever needing the EFO/OBI 'protocol' branch in HCAO at all. This can be browsed [here](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000272).
Note that the change to EFO:0010892 'hydrolisis collection protocol' above won't be available to you until the next HCAO release (May 19th). So in the meantime, I'd suggest you use EFO:0011026 'enzyme-free chemical dissociation' instead. In fact, please let us know if you'd need the 'hydrolysis' term at all.

Looking forward to hearing from you, thanks,

Paola (and Zoe)

**Comment by rachadele** [comment] 2021-04-28 17:08
Hi Paola,
'enzyme-free chemical dissociation' works just fine, no need for the hydrolysis term. Thanks!

**Comment by paolaroncaglia** [comment] 2021-04-29 11:34
Hi @pnejad and @rachadele,
Thanks. I will only fix the typo in EFO:0010892 'hydrolisis collection protocol' then. As for the broader discussion on validation report, schema and ontology branches, I made a note in the agenda for our next monthly curators meeting (May 12th). 

Hi @aaclan-ebi ,
This ticket may be closed I believe, at least from my side. Thanks!

**Comment by aaclan-ebi** [comment] 2021-04-29 13:05
I believe we usually close tickets by end of sprint. They're in the Done pipeline in zenhub for now. 

Thanks, everyone for all the efforts here!

**Closed** 2021-05-04 14:33 UTC
Labels: operations
