### ISSUE TITLE
Create map of local IDs to UUIDs for a given project

### ISSUE THREAD

**Issue by justincc** [ebi-ait/hca-ebi-dev-team#40] opened 2020-01-28 17:10 UTC
As part of the small 'r' release, wranglers need a map of local IDs in a spreadsheet to UUIDs of those documents in ingest. This is so that when they can extract the right information from their spreadsheets in order to produce a small 'r' release.

UUIDs are already inserted in spreadsheets submitted after we implement this for update purposes. However, there are a bunch of projects/submissions that are earlier than this date where they also need UUID/local ID relationships.

Therefore, for a given project we need to produce this mapping. We'll do this as a flat file rather than trying to insert this in spreadsheets after the fact, since a flat file will be much easier to produce given competing priorities. If this proves in sufficient we can look at going on to a spreadsheet insertion solution.

The relationships required are in [this doc](https://docs.google.com/spreadsheets/d/1hugdg072_NMsIu1OtES7vqfM2EOl3o5urD0d6vmbpgk/edit#gid=0). Because local IDs may be identical across entity types (e.g. a process and a cell suspension may conceivably have the same local ID), this mapping file also needs to contain the entity type (cell suspension, donor organism, etc.).

The list of projects they need this done for is [also in the spreadsheet](https://docs.google.com/spreadsheets/d/1hugdg072_NMsIu1OtES7vqfM2EOl3o5urD0d6vmbpgk/edit#gid=1966952358).

Strictly speaking, we (dev) could produce all the mappings ourselves using whatever facility we produce, as we know all the required project UUIDs. However, we are better off making a script executable by anyone in case we need to do this for some other project in the future.

**Acceptance criteria**
* [x] There is some facility (most probably a script) by which a wrangler can submit a project UUID and receive back a map (probably in a file) which contains all the local ID/UUID relationships requested in the spreadsheet above.
* [ ] The wrangler who needs to use this script can understand the output format, probably by making the output self describing.

**Comment by justincc** [comment] 2020-01-28 17:11
@ESapenaVentura, @zperova, @lauraclarke please say if the problem description is not accurate.

**Comment by zperova** [comment] 2020-01-28 17:18
after a brief discussion with @ESapenaVentura and @mshadbolt it looks like @mshadbolt R package might be useful to do the mapping

**Comment by justincc** [comment] 2020-01-28 17:20
@zperova You mean to actually implement this entirely or to consume the mapping file produced?

**Comment by lauraclarke** [comment] 2020-01-28 18:16
Please bear in mind this mapping needs to be produced asap, ideally by the end of Friday 31st. If the script can't be written and be functional so someone else can run it before the end of tomorrow, resorting to a process the devs run to provide the wranglers with an output file is an acceptable solution.

**Comment by zperova** [comment] 2020-01-29 09:13
@justincc as of now we plan to consume the mapping file produced. @mshadbolt might be better suited to answer this question, I am not familiar with her R package.

**Comment by mshadbolt** [comment] 2020-01-29 09:42
@justincc I think it would be great if the dev team could come up with the id matching and I can work on making it easier to then incorporate into spreadsheets

**Comment by rolando-ebi** [comment] 2020-01-29 10:09
@mshadbolt 

If the script I make produces a dictionary/hashmap of UUID -> local_id, would that be sufficient as input to your R script?

e.g a big JSON object that looks like:
```
{
  "<uuid>" : "<local_id>",
  ...
  ...
}
```

**Comment by lauraclarke** [comment] 2020-01-29 10:10
Is there an advantage to having the entity type in the list so there can be some double checking you are looking at the right thing?

**Comment by rolando-ebi** [comment] 2020-01-29 10:13
Sure I can partition the maps then as:

```
{
  "<schema_entity_type>": {
     "<uuid>" : "<local_id>",
     ...
     ...
  },
  ...
  ...
}
```

e.g

```
{
  "specimen_from_organism": {
     "<uuid>" : "<local_id>",
     ...
     ...
  },
  ...
  ...
}
```

**Comment by rolando-ebi** [comment] 2020-01-29 10:19
@lauraclarke @mshadbolt Let me know how you want the output to look, I can begin work on the script then

**Comment by lauraclarke** [comment] 2020-01-29 10:25
@mshadbolt's call as she is the one who will need to use it

**Comment by mshadbolt** [comment] 2020-01-29 11:15
sorry I was in a meeting

@rolando-ebi having the entity type is useful and I will be able to work with the mapping as you described, will you provide one per project? Or if one big file can we also partition the projects higher than the entities?

Also wanted to clarify that we only need this for the spreadsheets we can't currently download with uuids

**Comment by lauraclarke** [comment] 2020-01-29 11:28
@mshadbolt @rolando-ebi Assuming it isn't dramatically more effort, I would suggest getting it for all the spreadsheets as then there can be a bit of checking to compare the UUID/id pairs in this dump to the UUID/id pairs in a spreadsheet to make sure there aren't any off by one errors or something

**Comment by rolando-ebi** [comment] 2020-01-29 12:51
@mshadbolt 

> having the entity type is useful and I will be able to work with the mapping as you described, will you provide one per project?

Yes I can provide one per project. By the way by project I assume you mean submission, since a spreadsheet has a corresponding submission but not necessarily a corresponding project. 

>  Or if one big file

It's more robust to have this script output per submission since it'll likely be long-running for large submissions. I can write a small overlay for the script to accept a list of project/submission IDs and run the script on each.

**Comment by lauraclarke** [comment] 2020-01-29 12:53
> Yes I can provide one per project. By the way by project I assume you mean submission, since a spreadsheet has a corresponding submission but not necessarily a corresponding project.
> 

@rolando-ebi this statement confuses me. Spreadsheets explicitly reference projects but hold no concept of submission?

**Comment by rolando-ebi** [comment] 2020-01-29 12:57
A spreadsheet always results in the creation of a submission, sometimes results in the creation of a project. Also all metadata entities are explicitly associated with a submission, some aren't explicitly associated with a project. The discussions we were having about the domain model were motivated by the ambiguous understanding of what a project is (is it metadata/metadata-container/both). Right now projects aren't reliable containers of metadata, submissions are.

**Comment by lauraclarke** [comment] 2020-01-29 13:00
Okay so to make sure I have understood this correctly

From an ingest core perspective, submission is the logical query as a submission is a container for a particular set various metadata entities given to ingest at the same time which may or may have a project associated with them

From a spreadsheet perspective, spreadsheets right now always contain projects but never reference a specific submission event so projects make sense as the primary unique entity to reference a spreadsheet with 

@mshadbolt @rolando-ebi do those two viewpoints make sense

**Comment by rolando-ebi** [comment] 2020-01-29 13:08
Both make sense, but regarding the second viewpoint: Unfortunately projects can't reliably identify a spreadsheet. Since projects are metadata, and can be updated, there are different versions of the "same" project. One of these versions can be used to determine the original spreadsheet submission (most likely the oldest, but not guaranteed). If we want confidence in the scripts output we should provide submission IDs. The wranglers can use the Ingest UI project search page to find the exact submission ID for the desired spreadsheet.

**Comment by mshadbolt** [comment] 2020-01-29 13:08
@lauraclarke that makes sense to me

@rolando-ebi yes we will be able to figure out the project id from the submission id

**Comment by rolando-ebi** [comment] 2020-01-29 13:14
@mshadbolt 

> yes we will be able to figure out the project id from the submission id

It's the submission IDs the script needs; if you have them already then it's all good.

**Comment by ESapenaVentura** [comment] 2020-01-29 13:54
@rolando-ebi they are in the spreadsheet justin mentions https://docs.google.com/spreadsheets/d/1hugdg072_NMsIu1OtES7vqfM2EOl3o5urD0d6vmbpgk/edit#gid=1966952358

**Comment by rolando-ebi** [comment] 2020-01-29 13:55
Ahh I missed that, thanks

**Comment by rolando-ebi** [comment] 2020-01-29 14:59
@mshadbolt what's the ID field for project entities? Is it `project_short_name`?

**Comment by mshadbolt** [comment] 2020-01-29 15:12
yep they will work

**Comment by rolando-ebi** [comment] 2020-01-29 15:13
Generated output for two submissions:

Submission `8b5feb5e-9039-4c54-9e79-053e490c141a`
```
{
    "cell_suspension": {
        "10510764-ed13-4405-bd85-578abdc9ada2": "PP001_suspension",
        "1bcd1629-fba5-4dd5-92d3-97f7d896464d": "PP002_suspension",
        "1cf9b45c-268c-4934-9203-f9e16a90d46d": "PP020_suspension",
        "2bba3f76-1959-46ed-bea8-c0ba4fc13248": "PP018_suspension",
        "71785992-f5eb-41e2-9c0c-9435d2fa33aa": "PP019_suspension",
        "788f3a1c-9369-4900-83ab-594b241620c7": "PP005_suspension",
        "78b08aea-c194-4aa1-9e2e-56df9649bef1": "PP013_suspension",
        "7e5f6787-ab75-43c0-b284-dfeb208abf75": "PP012_suspension",
        "849419b1-77af-43aa-8ce9-6438ddee7420": "PP003_suspension",
        "8d1b11e2-2bdd-4dfe-b5af-b13bf5550d23": "PP010_suspension",
        "ac1e511f-fa9e-47b9-8b2d-b95b7e23d4ca": "PP014_suspension",
        "b29ca10d-b611-4ba2-a1f3-db38079aa9db": "PP004_suspension",
        "b72a54dc-69d7-41c7-a951-2695a7dcf76e": "PP011_suspension",
        "bf6604be-4692-43d9-8ac7-25476e2a98bc": "PP009_suspension",
        "cf7767c4-1daa-4d43-8155-65f30325e936": "PP006_suspension",
        "fa6a84ba-f9de-4302-8b72-e940658e888d": "PP017_suspension"
    },
    "donor_organism": {
        "4b7a3de7-94db-4507-b1f9-c3931f9f3aa5": "Blood_donor_B",
        "8b5774b2-2aba-4b90-8fa0-c7f69207802c": "Tissue_donor_1",
        "95822e01-44a7-420b-92fc-b001460b1d13": "Tissue_donor_2",
        "b09a1e10-3c38-4bb3-8553-d762810a6fb7": "Blood_donor_A"
    },
    "library_preparation_protocol": {
        "e953a093-f5ab-46df-9223-a492f4775d44": "PP001_library"
    },
    "project": {
        "4a95101c-9ffc-4f30-a809-f04518a23803": "HumanTissueTcellActivation"
    },
    "specimen_from_organism": {
        "03a73511-bdeb-47e0-8c1d-588fdbe8bb66": "PP020",
        "0ec78ea7-1fc1-47c6-9081-f9fb622eab8c": "PP018",
        "427e0abb-3d3e-4d59-a13e-6fc18bf81d16": "PP004",
        "46cbd6a3-1ba4-4f57-b27d-4e2b918b0d4c": "PP017",
        "55c59b93-6ce2-4d53-a7b8-5573d4f962fb": "PP003",
        "59a13e80-0c0b-40f5-b31a-a78fdbe0fe5a": "PP014",
        "85a0036b-fb11-40b5-b805-0af94bceee23": "PP013",
        "9a79497c-a825-449c-a605-ed4e1c5dd06c": "PP012",
        "a3c3f746-aa00-4138-abe1-ea8ac32f0b51": "PP002",
        "c2fed28d-cdd4-4fb4-bb94-5681dc99f52d": "PP006",
        "c9abc146-67f0-4e67-8383-c5ba5f1fc690": "PP010",
        "d02c3fdd-5c85-4e91-8585-111b4802379c": "PP005",
        "dfe889d8-86c0-4f50-adde-55bb58bec1ea": "PP001",
        "ed854de5-c872-4603-abc1-85c4e30b541b": "PP009",
        "edd28ba8-0bb3-476c-9079-d01b939617b0": "PP019",
        "ef3a770b-6bd5-44d3-8638-f2747d7412f1": "PP011"
    }
}
```

Submission `668791ed-deec-4470-b23a-9b80fd133e1c`

```
{
    "cell_suspension": {
        "0aabed05-6a89-4141-9384-828a33581419": "17-010-R-A",
        "1d3e48d7-d80f-4b99-85bd-04ff393288e7": "17-011-R-B",
        "932000d6-c63b-40f0-bdd5-469fa4db8be2": "SC-L-B",
        "b1b6ea44-e0b7-425a-9faa-51ecff56783e": "17-011-R-A",
        "eb32bfc6-e7be-4093-8959-b8bf27f2404f": "SC-L-A"
    },
    "collection_protocol": {
        "3030903f-4a4b-4b30-ab93-3b10183181e0": "Wong-retina collection"
    },
    "dissociation_protocol": {
        "2509f42a-0328-4e33-8d21-79d37560d846": "wong-retina-dissociation"
    },
    "donor_organism": {
        "427c0a62-9baf-42ab-a3a3-f48d10544280": "17-011",
        "66b7152c-8e94-412b-b0e4-f8fbf554df5a": "17-010",
        "b8049daa-7458-47bf-8ec2-3f5c56d2cb34": "SC"
    },
    "enrichment_protocol": {
        "ba595d79-aa43-4e3a-ad10-89f92ef4f22f": "wong-cell-size-selection"
    },
    "library_preparation_protocol": {
        "fa99959f-faa2-4d69-a092-48333e59f5f3": "10X_3GEX_v2"
    },
    "process": {
        "1116b396-448e-4dd1-b9c9-78357c511e15": "Retina_2_repB",
        "25999eea-6f12-40a8-aecf-d1524c7cf564": "process_id_7",
        "262f55a3-d03d-49ae-8080-1a6208fddb4f": "Retina_3_repA",
        "2f8a07c2-4a6b-47ac-a304-0dead66eee9e": "Retina_1",
        "3ad5d964-6c2c-4adc-badb-9100ceada68c": "process_id_8",
        "4054b722-a585-4e90-8d74-a02fb4d98202": "process_id_5",
        "48a0c58c-ea67-4014-8752-6339de02b70e": "process_id_1",
        "8b81f0c2-3b57-4072-8a10-c169fece543e": "Retina_2_repA",
        "98c88684-6469-4bb3-90aa-57a4ea101244": "process_id_4",
        "a5e37780-0b71-4610-8a7c-26142dedfcec": "process_id_2",
        "ad220152-0eb4-4f85-a03e-c7e81ea3f167": "Retina_3_repB",
        "b360251f-7550-4c08-b576-781858554ea1": "process_id_6",
        "e511e7ff-e67c-4eb3-b0db-13aecefb5486": "process_id_3"
    },
    "project": {
        "8185730f-4113-40d3-9cc3-929271784c2b": "WongAdultRetina"
    },
    "sequence_file": {
        "1016adeb-cdc3-47d6-a89e-771c763dd2e7": "Retina_Wong_scRNA_Sample2_R2.fastq.gz",
        "15f64718-69cf-462c-9704-e8a1f54c27c8": "Retina_Wong_scRNA_Sample3_R2.fastq.gz",
        "30040306-be5c-48f9-b221-e666e279ab5b": "Retina_Wong_scRNA_Sample4_I1.fastq.gz",
        "33682180-6cdf-4d0c-9fe0-e1c029ac13b2": "Retina_Wong_scRNA_Sample1_R1.fastq.gz",
        "39255288-6791-45b0-ac7e-b3ef4c981a3b": "Retina_Wong_scRNA_Sample4_R1.fastq.gz",
        "52149e21-dcd2-4288-a5eb-e526c3dcf745": "Retina_Wong_scRNA_Sample5_R2.fastq.gz",
        "6bd884d2-fccf-4227-8efc-184751527dfb": "Retina_Wong_scRNA_Sample2_R1.fastq.gz",
        "6d52232d-dc77-4070-bdb1-9bb0ee59d309": "Retina_Wong_scRNA_Sample5_R1.fastq.gz",
        "799f314f-7c6c-4981-be36-8e1310bf38e6": "Retina_Wong_scRNA_Sample3_I1.fastq.gz",
        "9f8f5212-0749-460b-9a46-2949dea45d52": "Retina_Wong_scRNA_Sample4_R2.fastq.gz",
        "a7b21a25-e76e-420d-8892-538062bfefbf": "Retina_Wong_scRNA_Sample3_R1.fastq.gz",
        "b01b2e61-3ebd-48cc-b071-f2e8cb42ff7c": "Retina_Wong_scRNA_Sample1_I1.fastq.gz",
        "e0efcd8d-8433-4b40-9eee-11dafb699a5a": "Retina_Wong_scRNA_Sample5_I1.fastq.gz",
        "e92c42c7-f238-44ea-b147-e199b768d450": "Retina_Wong_scRNA_Sample1_R2.fastq.gz",
        "f6407a7a-eecc-4735-a96a-b8bb634118e4": "Retina_Wong_scRNA_Sample2_I1.fastq.gz"
    },
    "sequencing_protocol": {
        "a166be3d-6e84-4058-a1bd-edf90cf3ee88": "HiSeq2500_200cycle"
    },
    "specimen_from_organism": {
        "1dda6a28-cbaa-4506-be47-fa117e8f463c": "17-011-R",
        "252b008d-8b5a-450c-a17c-4e779a17ff26": "17-010-R",
        "edc72947-b776-4150-8bfe-b7331acfa66f": "SC-L"
    }
}
```

If this looks ok I'll write up a bit of documentation and commit the script to one of our repos

**Comment by rolando-ebi** [comment] 2020-01-29 15:25
Script and readme here: https://github.com/ebi-ait/hca-ebi-dev-team/tree/master/scripts/spreadsheet-id-mapper

**Comment by mshadbolt** [comment] 2020-01-29 15:27
hi @rolando-ebi thanks for your work on this. The initial output looks great I will try it out and get back to you if I have any issues

**Comment by mshadbolt** [comment] 2020-01-30 09:35
Hi @rolando-ebi , a couple of questions. Is the expected behaviour for the script to get the uuids for all the entities or just a subset? In the two examples above, the first has a subset of the entities in the submission while the second has all entities. Or maybe its because the first is an update submission...hmmm I am not sure how we would then merge these files for multiple submissions for one project.

I also tried to run the script with this submission: 0948a727-228f-4cfc-857e-6243c6aed08d (https://api.ingest.data.humancellatlas.org/submissionEnvelopes/5cdb0344d96dad000858fff4 ) and it seems to run forever, I have to keyboard interrupt to get it to stop, the traceback I get when I stop it is:
```
Generating mapping for submission at https://api.ingest.data.humancellatlas.org/submissionEnvelopes/5cdb0344d96dad000858fff4
^CTraceback (most recent call last):
  File "spreadsheet_id_mapper.py", line 94, in <module>
    main(ingest_api_url, submission_uuid)
  File "spreadsheet_id_mapper.py", line 81, in main
    mapping = uuid_entity_id_map(submission_resource, ingest_api)
  File "spreadsheet_id_mapper.py", line 74, in uuid_entity_id_map
    return _uuid_entity_id_map(chain(biomaterials, files, processes, protocols, projects))
  File "spreadsheet_id_mapper.py", line 27, in _uuid_entity_id_map
    for entity in entities:
  File "/Users/mshadbolt/Documents/wrangling_work/insert_uuids_into_spreadsheets/venv/lib/python3.7/site-packages/ingest/api/ingestapi.py", line 270, in get_related_entities
    for entity in self.get_all(entity_uri, entity_type):
  File "/Users/mshadbolt/Documents/wrangling_work/insert_uuids_into_spreadsheets/venv/lib/python3.7/site-packages/ingest/api/ingestapi.py", line 259, in get_all
    r = self.get(next_url, headers=self.get_headers())
  File "/Users/mshadbolt/Documents/wrangling_work/insert_uuids_into_spreadsheets/venv/lib/python3.7/site-packages/ingest/api/ingestapi.py", line 37, in get
    return self.session.get(url, **kwargs)
  File "/Users/mshadbolt/Documents/wrangling_work/insert_uuids_into_spreadsheets/venv/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/Users/mshadbolt/Documents/wrangling_work/insert_uuids_into_spreadsheets/venv/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/mshadbolt/Documents/wrangling_work/insert_uuids_into_spreadsheets/venv/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/mshadbolt/Documents/wrangling_work/insert_uuids_into_spreadsheets/venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/mshadbolt/Documents/wrangling_work/insert_uuids_into_spreadsheets/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Users/mshadbolt/Documents/wrangling_work/insert_uuids_into_spreadsheets/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/mshadbolt/Documents/wrangling_work/insert_uuids_into_spreadsheets/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/Users/mshadbolt/Documents/wrangling_work/insert_uuids_into_spreadsheets/venv/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 313, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/Users/mshadbolt/Documents/wrangling_work/insert_uuids_into_spreadsheets/venv/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1839, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
KeyboardInterrupt

```

**Comment by rolando-ebi** [comment] 2020-01-30 10:27
@mshadbolt 

> Is the expected behaviour for the script to get the uuids for all the entities or just a subset? ...maybe its because the first is an update submission.

The script is working as expected; it gets the mapping for all entities in a submission. If you want the mapping for the original submission you have to provide that submission's UUID, not the update submission UUID. The update submission only contains a subsets of the entities you're after, the original submission contains all of them.

> ..hmmm I am not sure how we would then merge these files for multiple submissions for one project.

This is functionality I can add if needs be but it shouldn't be necessary if you provide only original submission IDs

> I also tried to run the script with this submission: 0948a727-228f-4cfc-857e-6243c6aed08d (https://api.ingest.data.humancellatlas.org/submissionEnvelopes/5cdb0344d96dad000858fff4 ) and it seems to run forever

Taking a look

**Comment by lauraclarke** [comment] 2020-01-30 10:28
@rolando-ebi will the original submission contain any updates which were made in later submissions? say new data was added?

**Comment by rolando-ebi** [comment] 2020-01-30 10:31
Update submissions don't add new data. If there were submissions that added new data(e.g add new bundles submissions) then I'll have to implement the merge functionality mentioned in the previous comment. Did we ever do any of those kinds of submission in the end?

**Comment by lauraclarke** [comment] 2020-01-30 10:34
Yes, at least for the Meyer Tissue sensitivity dataset or was that done via re-ingestion @mshadbolt 

A new question for updates, if the original submission envelope id is contained will it return local ids as used in the original submission or local ids as used in the most recent submission?

**Comment by mshadbolt** [comment] 2020-01-30 10:36
I don't think we have ever done an update that adds bundles, I didn't think that this was possible.

The Meyer Tissue Stability dataset was a reingestion that retained the original uuid

**Comment by rolando-ebi** [comment] 2020-01-30 10:38
@lauraclarke 
> A new question for updates, if the original submission envelope id is contained will it return local ids as used in the original submission or local ids as used in the most recent submission

That's a good point, it will return the local IDs as they were in the original submission, which is probably not what we want. I can add functionality to the script to fetch the latest local ID in that case. Would need to make it clear then that the script isn't doing the mapping per submission, but rather based on the latest versions of the entities in a submission.

**Comment by rolando-ebi** [comment] 2020-01-30 10:45
@mshadbolt 
Submission `0948a727-228f-4cfc-857e-6243c6aed08d` completed for me after a few minutes. It has about 10k entities so takes a bit longer than some of the others.

**Comment by mshadbolt** [comment] 2020-01-30 10:46
oh ok I will try again, last night I left it running for hours and it never completed.

**Comment by mshadbolt** [comment] 2020-01-30 10:53
You are right it did finish after about 4 minutes, gotta have more patience

**Comment by lauraclarke** [comment] 2020-01-30 10:57
> @lauraclarke
> 
> > A new question for updates, if the original submission envelope id is contained will it return local ids as used in the original submission or local ids as used in the most recent submission
> 
> That's a good point, it will return the local IDs as they were in the original submission, which is probably not what we want. I can add functionality to the script to fetch the latest local ID in that case. Would need to make it clear then that the script isn't doing the mapping per submission, but rather based on the latest versions of the entities in a submission.
> 
> Let me know if I should add this.

@mshadbolt can you think of anywhere where we might have updated local ids which could create an issue here?

**Comment by mshadbolt** [comment] 2020-01-30 11:36
@rolando-ebi to my knowledge we haven't updated the local ids in an update submission. I also think that it would be a fairly unlikely scenario to occur, as we generally make updates to the metadata fields rather than the ids. But i guess it _**could**_ happen in the future.

One scenario I just thought of is if someone mistakenly called two biomaterials with the same ID. I just did a test of this where I named two donors with the same id in the spreadsheet and uploaded to ingest. Interestingly ingest only retains one of the donors with the same id. Then when you download the spreadsheet from the ui it has one row without a uuid and one without it. So in that case we would want to update the id.

**Comment by mshadbolt** [comment] 2020-01-30 11:38
but in my opinion something like the same ids for two biomaterials should be caught somewhere in validation

**Comment by rolando-ebi** [comment] 2020-01-30 11:38
> One scenario I just thought of is if someone mistakenly called two biomaterials with the same ID. I just did a test of this where I named two donors with the same id in the spreadsheet and uploaded to ingest. Interestingly ingest only retains one of the donors with the same id

I think what should happen there is an error from spreadsheet-conversion component when it sees duplicate IDs in the spreadsheet

**Comment by mshadbolt** [comment] 2020-01-30 11:40
Here's a submission that I did where I have two donors with the same id and two collection protocols with the same id where only one of the two gets added to ingest https://ui.archive.data.humancellatlas.org/submissions/detail/5e32c0090abaea1b785b6ccc/overview

**Comment by rolando-ebi** [comment] 2020-01-30 11:41
Yeah this is a bug imo and should be fixed in another ticket

**Closed** 2020-02-14 14:57 UTC
Labels: medium
